export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    recoveryRequest: '/auth/recovery/request',
    recoveryConfirm: '/auth/recovery/confirm',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  programs: '/programs',
  courses: '/courses',
  students: '/students',
  graph: (programId: string) => `/curriculums/${programId}/graph`,
  profile: (studentId: string) => `/students/${studentId}/profile`,
  student: (studentId: string) => `/students/${studentId}`,
  studentPrograms: (studentId: string) => `/students/${studentId}/programs`,
  history: (studentId: string) => `/students/${studentId}/history`,
  progress: (studentId: string, programId: string) =>
    `/students/${studentId}/progress/${programId}`,
  doubleProgram: (studentId: string) => `/students/${studentId}/double-program`,
  simulation: {
    failure: '/simulation/failure',
    cancellation: '/simulation/cancellation',
    postponement: '/simulation/postponement',
  },
  scenarios: '/scenarios',
  studentScenarios: (studentId: string) => `/students/${studentId}/scenarios`,
  compareScenarios: '/scenarios/compare',
  admin: {
    overview: '/admin/overview',
    dashboard: '/admin/dashboard',
    systemStatus: '/admin/system-status',
    users: '/admin/users',
    resetUserPassword: (userId: string) => `/admin/users/${userId}/reset-password`,
    versions: '/admin/versions',
    dependencies: '/admin/dependencies',
    ocrStatus: '/admin/ocr/status',
  },
  documents: '/admin/curriculum-documents',
  chatSessions: '/chat/sessions',
  chatMessages: (sessionId: string) => `/chat/sessions/${sessionId}/messages`,
  chatRagQueries: (sessionId: string) => `/chat/sessions/${sessionId}/rag-queries`,
  ragRetrieve: '/rag/retrieve',
  llmGenerate: '/llm/generate',
  llmConnect: '/llm/connect',
} as const
