"""initial schema

Revision ID: 69faf3bee003
Revises: 
Create Date: 2026-05-15 09:19:29.425799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69faf3bee003'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('total_creditos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('STUDENT', 'ADMIN', 'ADVISOR', name='userrole'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('curriculum_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('programa_id', sa.String(length=64), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=100), nullable=False),
    sa.Column('estado_procesamiento', sa.Enum('PENDIENTE', 'EXTRAYENDO_TEXTO', 'OCR', 'PROCESANDO', 'VALIDANDO', 'CONVERTIDO_A_GRAFO', 'ERROR', name='documentprocessingstatus'), nullable=False),
    sa.Column('porcentaje_progreso', sa.Integer(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['programa_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('programa_id', sa.String(length=64), nullable=False),
    sa.Column('nombre_version', sa.String(length=50), nullable=False),
    sa.Column('anio_vigencia', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['programa_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.String(length=64), nullable=False),
    sa.Column('codigo_estudiantil', sa.String(length=20), nullable=False),
    sa.Column('semestre_actual', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_estudiantil'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('estudiante_id', sa.String(length=64), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version_malla_id', sa.String(length=64), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('semestre_sugerido', sa.Integer(), nullable=False),
    sa.Column('electiva', sa.Boolean(), nullable=False),
    sa.Column('area_opcional', sa.String(length=100), nullable=True),
    sa.Column('descripcion_opcional', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_malla_id'], ['curriculum_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_malla_id', 'codigo', name='uq_course_version_code')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('documento_malla_id', sa.String(length=64), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['documento_malla_id'], ['curriculum_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_extractions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('documento_malla_id', sa.String(length=64), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=False),
    sa.Column('metodo_extraccion', sa.Enum('TEXTO_PDF', 'OCR_IMAGEN', 'MIXTO', name='extractionmethod'), nullable=False),
    sa.Column('confianza_ocr', sa.Float(), nullable=False),
    sa.Column('fecha_procesamiento', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['documento_malla_id'], ['curriculum_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_malla_id')
    )
    op.create_table('program_enrollments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('estudiante_id', sa.String(length=64), nullable=False),
    sa.Column('programa_id', sa.String(length=64), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['programa_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('estudiante_id', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_history',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('estudiante_id', sa.String(length=64), nullable=False),
    sa.Column('materia_id', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.Enum('APROBADA', 'REPROBADA', 'EN_CURSO', 'PENDIENTE', 'DISPONIBLE', 'BLOQUEADA', name='coursestatus'), nullable=False),
    sa.Column('semestre_cursado', sa.Integer(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id', 'materia_id', name='uq_history_student_course')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('chat_sesion_id', sa.String(length=64), nullable=False),
    sa.Column('emisor', sa.Enum('USUARIO', 'ASISTENTE', name='chatsender'), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fuentes_opcionales', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chat_sesion_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_dependencies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('materia_id', sa.String(length=64), nullable=False),
    sa.Column('materia_requerida_id', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.Enum('PREREQUISITO', 'CORREQUISITO', name='dependencytype'), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['materia_requerida_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('escenario_id', sa.String(length=64), nullable=False),
    sa.Column('materia_id', sa.String(length=64), nullable=False),
    sa.Column('tipo_evento', sa.Enum('PERDIDA', 'CANCELACION', 'APLAZAMIENTO', 'APROBACION', name='scenarioeventtype'), nullable=False),
    sa.ForeignKeyConstraint(['escenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('escenario_id', sa.String(length=64), nullable=False),
    sa.Column('materia_id', sa.String(length=64), nullable=False),
    sa.Column('estado_simulado', sa.Enum('APROBADA', 'REPROBADA', 'EN_CURSO', 'PENDIENTE', 'DISPONIBLE', 'BLOQUEADA', name='coursestatus'), nullable=False),
    sa.ForeignKeyConstraint(['escenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggested_routes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('escenario_id', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('semestre_estimado_graduacion', sa.Integer(), nullable=False),
    sa.Column('duracion_estimada', sa.Integer(), nullable=False),
    sa.Column('dificultad', sa.Enum('BAJA', 'MEDIA', 'ALTA', name='difficulty'), nullable=False),
    sa.Column('carga_trabajo', sa.Enum('BAJA', 'MEDIA', 'ALTA', name='workload'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['escenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_queries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('chat_mensaje_id', sa.String(length=64), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('contexto_recuperado', sa.Text(), nullable=False),
    sa.Column('fuentes_consultadas', sa.Text(), nullable=False),
    sa.Column('modelo_local', sa.Enum('GEMMA', 'LLAMA', 'MISTRAL', 'OTRO', name='localmodel'), nullable=False),
    sa.ForeignKeyConstraint(['chat_mensaje_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_mensaje_id')
    )
    op.create_table('route_steps',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ruta_id', sa.String(length=64), nullable=False),
    sa.Column('materia_id', sa.String(length=64), nullable=False),
    sa.Column('semestre_sugerido', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['ruta_id'], ['suggested_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_steps')
    op.drop_table('rag_queries')
    op.drop_table('suggested_routes')
    op.drop_table('scenario_results')
    op.drop_table('scenario_events')
    op.drop_table('course_dependencies')
    op.drop_table('chat_messages')
    op.drop_table('academic_history')
    op.drop_table('scenarios')
    op.drop_table('program_enrollments')
    op.drop_table('document_extractions')
    op.drop_table('document_chunks')
    op.drop_table('courses')
    op.drop_table('chat_sessions')
    op.drop_table('students')
    op.drop_table('curriculum_versions')
    op.drop_table('curriculum_documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('programs')
    # ### end Alembic commands ###
